# Generated by Django 5.1.2 on 2025-02-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Successful'), (3, 'Unsuccessful')], default=1),
        ),
    ]
